[project]
name = "po-dbt"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12.10, <3.13"
dependencies = [
    "dbt-bigquery>=1.9.1",
]

[dependency-groups]
dev = [
    "sqlfluff>=3.3.1",
    "sqlfluff-templater-dbt>=3.3.1",
]
