# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'po_dbt'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'po_dbt'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# Variables
vars:
  session_timeout_minutes: 10  # Time in minutes after which a new session starts
  activity_refresh_days: 7  # Number of days to keep active refreshes
  attribution_window: 10  # Number of days to match MMP install date to first touch timestamp

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/
# directory as views. These settings can be overridden in the individual model
# files using the `{{ config(...) }}` macro.
models:
  po_dbt:
    # Config indicated by + and applies to all files under models/example/
    staging:
      +schema: staging
      +materialized: table
    dimensions:
      +schema: dimensions
    facts:
      +schema: facts
    intermediate:
      +schema: intermediate
      
      
seeds:
  po_dbt:
    +schema: seed_data